sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.8.0

before_install:
  - sudo apt-get update -y
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-get install -y python-flake8

install:
  - docker-compose build django

before_script:
  - flake8 hypermap

script:
  - docker-compose run django python manage.py test hypermap.aggregator --settings=hypermap.settings.test --failfast

branches:
  only:
    - master
    - registry
