language: python

python:
  - "2.7"

sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.8.0

before_install:
  - sudo apt-get update -y
  - sudo sudo install docker-ce
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-get install -y python-flake8
  - sudo sysctl -w vm.max_map_count=262144

install:
  - make build

before_script:
  - make flake

script:
  - make test

branches:
  only:
    - master
    - registry
