version: '2'
services:

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    image: terranodo/registry
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    environment:
      - REGISTRY_SEARCH_URL=elasticsearch+http://elasticsearch:9200/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - ALLOWED_HOSTS=['django',]
  celery:
    image: terranodo/registry
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=hypermap.celeryapp:app -B -l INFO
    environment:
      - REGISTRY_SEARCH_URL=elasticsearch+http://elasticsearch:9200/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - ALLOWED_HOSTS=['django',]
      - C_FORCE_ROOT=1

  maploom:
    image: terranodo/maploom
    command: grunt serve

  nginx:
    image: terranodo/nginx:registry
    links:
      - django
      - maploom
      - elasticsearch
    ports:
      - "80:80"
