version: '2'
services:


  solr:
    image: solr
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hypermap

  django:
    links:
      - solr
    environment:
      - REGISTRY_SEARCH_URL=solr+http://solr:8983

  celery:
    links:
      - solr
    environment:
      - REGISTRY_SEARCH_URL=solr+http://solr:8983

