version: '2'
services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"

  elasticsearch:
   image: elasticsearch
   ports:
        - "9200:9200"

  rabbitmq:
     image: rabbitmq
     ports:
        - "5672:5672"

  django:
    build: .
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch
      - rabbitmq:rabbit
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx
    links:
      - django:django
    ports:
      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  celery:
    image: celery
    links:
      - rabbitmq:rabbit
      - postgres:postgres
      - elasticsearch:elasticsearch
