version: '2'
services:

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    image: terranodo/registry
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    environment:
      - SEARCH_ENABLED=True
      - SEARCH_TYPE=elasticsearch
      - SEARCH_URL=http://elasticsearch:9200/
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - ALLOWED_HOSTS=['django',]
  celery:
    image: terranodo/registry
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=hypermap.celeryapp:app -B -l INFO
    environment:
      - SEARCH_ENABLED=True
      - SEARCH_TYPE=elasticsearch
      - SEARCH_URL=http://elasticsearch:9200/
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - C_FORCE_ROOT=1

  nginx:
    image: terranodo/nginx
    links:
      - django
    ports:
      - "80:80"
