version: '2'
services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"

  elasticsearch:
   image: elasticsearch
   ports:
        - "9200:9200"

  rabbitmq:
     image: rabbitmq
     ports:
        - "5672:5672"

  django:
    build: .
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - SEARCH_ENABLED=True
      - SEARCH_TYPE=elastic
      - SEARCH_URL=http://elastic/
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  nginx:
    image: nginx
    links:
      - django
    ports:
      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  celery:
    image: celery
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=hypermap.celeryapp:app -B -l INFO
    volumes:
      - .:/code
    environment:
      - DEBUG=True
      - SEARCH_ENABLED=True
      - SEARCH_TYPE=elastic
      - SEARCH_URL=http://elastic/
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
